### ISSUE TITLE
Error: Access to the path 'C:\Windows\system32\drivers\etc\hosts' is denied

### ISSUE THREAD

**Issue by Gladiacode** [WereDev/Wu10Man#26] opened 2020-08-24 12:03 UTC

**Comment by englishextra** [comment] 2020-08-24 12:10
@Gladiacode Tinywall?
![2020-08-24_150952](https://user-images.githubusercontent.com/537127/91043247-f1980a00-e61b-11ea-829d-92c9ade62dc6.png)

**Comment by Gladiacode** [comment] 2020-08-24 12:18
I do not have this program and need to install it?

**Comment by englishextra** [comment] 2020-08-24 12:23
@Gladiacode I meant that there is some program already working on your machine like Tinywall that locks hosts file. perhaps some antivirus holds hosts file.

**Comment by WereDev** [comment] 2020-08-24 14:58
That is correct.  If you are getting that error, that means some other process has a lock on that file.  If this is a work machine, it could also mean that there is some policy enacted by the domain that is locking the file as well, but I can't say I've run across that often.

Also, what version of Wu10Man are you running?  I thought I had updated that error in newer versions and added a check to try to identify the locking application.

**Comment by WereDev** [comment] 2020-09-09 23:11
@Gladiacode Is there any other information you can provide?  Did you identify what might keep keeping a lock on Hosts?  If there is anything else I can do to help, please let me know, though I might need a copy of recent logs.

Thanks.

**Comment by WereDev** [comment] 2020-09-19 22:26
I was able to reproduce this error only when Windows Defender was set to block the application.  Since this seems to be related to a known issue, I'm going to go ahead and close this issue.  Also as an FYI, I've moved this functionality to "Legacy" since this is proving to be a growing issue but has proven to not do much for blocking Windows Update.

Let me know if you have other issues or if there are other things I can help with.  Thanks.

**Closed by WereDev** 2020-09-19 22:26 UTC
